### ISSUE TITLE
Bash profile not picking up home-brew correctly

### ISSUE THREAD

**Issue by daroleary** [samsonnguyen/solium-boxen#13]
Running commands like:

brew --cellar [ran locally returns : /opt/boxen/homebrew/Cellar]
however called from ~/.bash_profile as `brew --cellar` returns /usr/local/homebrew/Cellar which doesn't exist. 

Likely nothing to do with configuration but likely once we know the fix we can add to the readme.

**Comment by samsonnguyen** [comment]
See https://github.com/samsonnguyen/puppet-solium/issues/6
